# Machine Learning Zoomcamp

## 1.7 Introduction to NumPy

Plan:
* Creating arrays.
* Multi-dimensional arrays.
* Randomly generated arrays.
* Element-wise operations.
    * Comparison operations.
    * Logical operations.
* Summarizing operations.

In [2]:
import numpy as np

In [5]:
np

<module 'numpy' from '/opt/homebrew/anaconda3/envs/ml-zoomcamp/lib/python3.11/site-packages/numpy/__init__.py'>

### Creating arrays.

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [11]:
a =np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [12]:
a[2]

np.int64(3)

In [14]:
a[2] = 10

In [15]:
a

array([ 1,  2, 10,  5,  7, 12])

In [16]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Multi-dimensional arrays.

In [19]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
n[0, 1]

np.int64(2)

In [23]:
n[0, 1] = 10
n

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [25]:
n[0]

array([ 1, 10,  3])

In [27]:
n[:, 1]

array([10,  5,  8])

In [28]:
n[:, 2] = [0, 1, 2]
n

array([[ 1, 10,  0],
       [ 4,  5,  1],
       [ 7,  8,  2]])

### Randomly generated arrays

In [32]:
np.random.rand(5, 2)

array([[0.17571717, 0.55849132],
       [0.65351853, 0.05008997],
       [0.4417938 , 0.15069852],
       [0.75047874, 0.34807767],
       [0.49174943, 0.81209087]])

In [42]:
np.random.seed(10)
np.random.rand(5, 2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [43]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [44]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

### Element-wise operations.

In [46]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [47]:
a + 1

array([1, 2, 3, 4, 5])

In [48]:
a / 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [49]:
10 + (a * 2)

array([10, 12, 14, 16, 18])

In [51]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [52]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

### Comparision operations

In [53]:
a >= 2

array([False, False,  True,  True,  True])

In [54]:
a > b

array([False, False,  True,  True,  True])

In [55]:
a[a > b]

array([2, 3, 4])

### Summarizing operations

In [56]:
a.min()

np.int64(0)

In [57]:
a.max()

np.int64(4)

In [58]:
a.sum()

np.int64(10)

In [59]:
a.mean()

np.float64(2.0)

In [60]:
a.std()

np.float64(1.4142135623730951)

In [61]:
n.min()

np.int64(0)